[tools]
# Tool directories and executables
icontools_dir = "/p/project1/ifces2-scalexa/tools/dwd_icon_tools/icontools"
extpar_input_dir = "/p/scratch/ifces2-scalexa/extpar-input-data"
extpar_dir = "/p/project1/ifces2-scalexa/tools/extpar/"
icon_build_dir = "/p/scratch/ifces2-scalexa/senf1/tmp/icon-build/build-jwc-gcc"

[project]
name = "hurricane-centric_paulette2020"
width_config = "width100km_reinit24h_single"
working_dir = "/p/scratch/ifces2-scalexa/senf1/tmp"

[reference]
# Reference grids and datasets
init_time = "20200907T000000Z"
expname = "ifces2-atlanXL-20200907-exp021"
input_grid = "/p/project1/ifces2-scalexa/input/data/icon/grids-extpar/atlanXL/atlanXL_R02B10_DOM02.nc"
input_icbc_dir = "/p/project1/ifces2-scalexa/input/data/icon/atlantic-cases/paulette/ifces2-atlanXL-20200907-exp021"
input_icbc_subdir = "NESTING"

[track]
# Hurricane track data
track_dir = "/p/project1/ifces2-scalexa/input/data/icon/atlantic-cases/derived-data/tracks/"
track_file = "ifces2-atlanXL-20200907-exp021-DOM02_paulette_best-fit.nc"

[domains]
# Domain configuration
segment_reinit_hours = 24.0
segment_length_added = 3.0
nests = 1
dom_width = [300.0] # in km

[output]
# Output directories
grid_basedir = "/p/scratch/ifces2-scalexa/senf1/data/icon/grids-extpar/"
icbc_basedir = "/p/scratch/ifces2-scalexa/senf1/data/icon/bc-init/"

# end of config
