[project]
name = "paulette-segments"
width_config = "width20km"

[paths]
# Core tool directories
icontools_dir = "/work/bb1174/models/icon/dwd_icon_tools/icontools"
extpar_input_dir = "/work/pd1167/extpar-input-data"
extpar_dir = "/work/bb1376/tools/extpar"
script_dir = "/work/bb1376/user/fabian/tools/pre-processing/grid-extpar"

# Data directories
base_grid = "/work/bb1376/data/icon/grids-extpar/atlanXL/atlanXL_R02B10_DOM02.nc"
output_base = "/work/bb1376/data/icon/grids-extpar"
track_dir = "/work/bb1376/user/fabian/data/icon/paulette-statistics"

[simulation]
expname = "ifces2-atlanXL-20200907-exp021"
segment_reinit_hours = 6.0
segment_length_added = 3.0
nests = 3

[domains]
dom_width = [60.0, 40.0, 20.0]  # in km